// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyDNhrySr79meukkK7D59isSrfoihApLSdI',
    appId: '1:340219657596:web:c94f8dc7a52d3d0132f8f9',
    messagingSenderId: '340219657596',
    projectId: 'website-gia-pha-6eca4',
    authDomain: 'website-gia-pha-6eca4.firebaseapp.com',
    storageBucket: 'website-gia-pha-6eca4.firebasestorage.app',
    measurementId: 'G-X7MWYRDJRQ',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: 'AIzaSyCFDMZcfDBk-StiaZXQojYxDkLS_obw-lo',
    appId: '1:340219657596:android:b8933653c0570d6b32f8f9',
    messagingSenderId: '340219657596',
    projectId: 'website-gia-pha-6eca4',
    storageBucket: 'website-gia-pha-6eca4.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: 'AIzaSyAFcZn-h9N70kXzLME5y89I3MYAZp-_edk',
    appId: '1:340219657596:ios:248fc03b8f53ae4832f8f9',
    messagingSenderId: '340219657596',
    projectId: 'website-gia-pha-6eca4',
    storageBucket: 'website-gia-pha-6eca4.firebasestorage.app',
    iosBundleId: 'com.example.websiteGiaPha',
  );
}
